Nachdem der source ocmalfind und so weiter braucht ist es das
einfachste das bei mir installierte GODI zu verwenden. Dazu in der
bash das file ~heinz/godi/godi-20050523/go.source sourcen. Und dann
einfach make machen. Das geht auf iglo und ema*

Wer lieber sein ocaml selbst installed, braucht ocaml, camlp4,
lablgtk2 und findlib.
